### ISSUE TITLE
Living / Twisted Garden in Map Solver

### ISSUE THREAD

**Issue by AardWolf** [DevJackSmith/mh-hunt-helper#23]
The pouring/not pouring +/- of the one changes the other as well. Both show up even if the mouse is only a living garden mouse. But in that case there are no mice listed in the twisted garden (but it says 2).

URL used: https://mhmaphelper.agiletravels.com/mice/Agitated%20Gentle%20Giant+Beast%20Tamer+Bloomed%20Sylvan+Camofusion+Caravan%20Guard+Carmine%20the%20Apothecary+Count%20Vampire+Crimson%20Commander+Cursed+Derr%20Lich+Dirt%20Thing+Funglore+Gilded%20Leaf+Goliath%20Field+Hired%20Eidolon+Limestone%20Miner+Lost%20Legionnaire+Menace%20of%20the%20Rift+Mermouse+Meteorite%20Miner+Mining%20Materials%20Manager+Mystic%20Scholar+Naturalist+Nightshade%20Masquerade+Pygmy%20Wrangler+Shadow%20Stalker+Spore%20Muncher+Stalagmite+Surgeon%20Bot+Swarm%20of%20Pygmy%20Mice+Technic%20Pawn+Toxic%20Avenger+Tri-dra+Vampire+Wolfskie

**Comment by DevJackSmith** [comment]
good catch! Thanks! Will fix!

**Comment by DevJackSmith** [comment]
fixed the +/- buttons as well as Carmine and Camofusion showing up in LG. Should have only been in TG.
