### ISSUE TITLE
Sunken City Solver Enhancement

### ISSUE THREAD

**Issue by AardWolf** [DevJackSmith/mh-hunt-helper#24]
Currently mice are only broken out by depth. Could they be broken into actual region, which has the depth attached?

**Comment by DevJackSmith** [comment]
hmm they can be. I will need to think about this one as I am trying to keep it simple. I want to add the 22 regions/zones/stages only in the attraction tool, not in the map helper. This is mostly due to having so many of them, that some mice will show lots of zones, cluttering up the space.

**Comment by groupsky** [comment]
If on each hunt the current zone as well as current depth is logged, then the mapper can use only the depth, while in other situations the zone can be used. To ease the separation a tagging system can be used.

**Comment by DevJackSmith** [comment]
the thing is how do i separate? building another relationship one to many = hunt to stage_name_two? Or maybe use it as a second stage, but then it would add up in the attraction tool. I also want something that will work for all locations+stages, not just one off for sunken.

**Comment by groupsky** [comment]
My suggestion is to use tags to separate stages - there could be a tag `ar-visible` or `ar-hidden` which would be inspected by the attraction tool and display/hide only stages with this tag. Similarly tags could be used for other tools to hint which stages to use.

**Comment by DevJackSmith** [comment]
moved the code to stages in v18.10.14. Will do migration in a week or so when all new stage names are automatically recorded.

**Comment by DevJackSmith** [comment]
did migration and cleanup, all sunken data should have detailed stages now

**Comment by DevJackSmith** [comment]
thanks again @groupsky
