### ISSUE TITLE
Extension: Add autopop link for Tsitu's CRE

### ISSUE THREAD

**Issue by DevJackSmith** [DevJackSmith/mh-hunt-helper#29]

**Comment by tsitu** [comment]
Priority: Low-Medium

We discussed integrating all of my bookmarklets (Map Solver, Marketplace Analyzer, Best Setup, and CRE) into your extension to centralize them and alleviate the burden of manually updating from end users. There are 2 main problems to solve here:

- Accessing the global user object, which may involve injecting a script tag from the content script into the DOM to read its variables. My browser extension knowledge is limited, but [this link](https://stackoverflow.com/questions/20499994/access-window-variable-from-content-script/20513730#20513730) might be relevant?
- Pulling updates from our repository - git submodules or perhaps something simpler

**Comment by DevJackSmith** [comment]
Thanks for writing it up.
Accessing user object is not an issue. I'm already doing it. Having your bookmarklet scripts do it, without changing them is the issue. Will have to try to run your scripts from different locations:  main script, injected script, popup script, background script. If none of those work out of the box, we will have to either create some kind of a wrapper or implement them as we implement autopop map solver now. In addition to all that we will need to add trigger buttons to the extension.

Keeping the bookmarklets updated in only one place means that we will need to either 
1. have a call to a url where the bookmarklet lives (preferable since the updates are independent then)
2. included as part of the extension package (submodule, or otherwise)

**Comment by tsitu** [comment]
Let me know if you're able to successfully run from any of those 4 locations.

Calling from URL is an excellent solution - for reference, here's our [minified CRE bookmarklet](https://raw.githubusercontent.com/tsitu/MH-Tools/gh-pages/src/bookmarklet/crebookmarklet.min.js).

**Comment by DevJackSmith** [comment]
done in 1.12.18

notes for future:
used main script as all others did not work for one reason or another.
