### ISSUE TITLE
Convertible tracker

### ISSUE THREAD

**Issue by DevJackSmith** [DevJackSmith/mh-hunt-helper#32]
Track convertibles like unstable curd, or any other item that opens and gives loot.

**Comment by DevJackSmith** [comment]
another vote for convertibles

**Comment by DevJackSmith** [comment]
@groupsky did the javascript part. Very nicely.
now I just need to do a few more things to complete it.

To start recording:
- create convertibles table: id - name
- create item table: id - name
- create converitble_item table: convertible_id - convertible_amount - item_id - item_amount
- create convertible intake that records convertibles and items

To start displaying:
- create db event to create aggregated convertibles table (via temp table and renaming)
- - create convertibles_aggr table: Convertible id - item id - rate (amount of item per convertible)
- create 2 views:
- - search by convertible:
- - - get item names and rate (amount of items per given convertible)
- - search by items:
- - - get convertible names and rate (amount of given items per this convertible)

**Comment by DevJackSmith** [comment]
might be able to reuse loot table for this one

**Comment by DevJackSmith** [comment]
to make this work we also need duplicate submit protection.

**Comment by groupsky** [comment]
There should be a per-user unique id of the journal log, that could serve as a duplicate protection, but I'm not sure when I'll have time to look into it.

Is there anything related for the hunt submission?

**Comment by DevJackSmith** [comment]
finished the first (recording) part, just need to add some views when i get time

**Comment by DevJackSmith** [comment]
I also need to create auto-backup for this new db. And add it to Tracker page

**Comment by DevJackSmith** [comment]
didn't find journal entry id, used asset_package_hash together with user id, but it turned out the same (not-changing). Need to find another duplicate protection.

**Comment by DevJackSmith** [comment]
Added first view, db aggregation event, auto-backup, and tracker stats.
Still need
- unique identifier (duplicate protection)
- second view
- Add it to extension

**Comment by DevJackSmith** [comment]
this has been done
