### ISSUE TITLE
Implement Moussu Picchu stages

### ISSUE THREAD

**Issue by tsitu** [DevJackSmith/mh-hunt-helper#33]
Similar to WWRift, the Wind/Rain levels in MoPi affect mouse populations/attraction proportions, and are located at `user["quests"]["QuestMoussuPicchu"]["elements"]["wind/rain"]["level"]`. Not sure how you'd implement this but it's vital for my tools 😀 

There are 5 levels and 25 combinations (pasted below for reference):

- none-none (Gouda / SB+ / GG)
- none-low (Windy / Rainy / Dragonvine)
- none-medium
- none-high
- none-max
- low-none
- low-low
- low-medium
- low-high
- low-max
- medium-none
- medium-low
- medium-medium
- medium-high
- medium-max
- high-none
- high-low
- high-medium
- high-high
- high-max
- max-none
- max-low
- max-medium
- max-High
- max-max (Ful'Mina 100% Dragonvine)

**Comment by DevJackSmith** [comment]
done

**Comment by tsitu** [comment]
@DevJackSmith 
Revised unique stages.

### None (Gouda / SB+ / GG)
- Nightshade Flower Girl, Nightshade Maiden, Spore Salesman, Breeze Borrower, Windy Farmer, Cloud Collector, Rainwater Purifier, Homeopathic Apothecary

### Wind (Windy Cheese)
- Low (Wind Watcher + Charming Chimer)
- Medium (Fluttering Flutist + Cycloness)
- High (Cycloness + Wind Warrior)
- Max (Wind Warrior = 100%)

### Rain (Rainy Cheese)
- Low (Rain Collector + Rain Wallower)
- Medium (Rain Summoner + Monsoon Maker)
- High (Monsoon Maker + Rainmancer)
- Max (Rainmancer = 100%)

### Storm (Dragonvine Cheese)
- Low (Thunder Strike + Violet Stormchild)
- Medium (Thunderlord + Thundering Watcher)
- High (Thundering Watcher + Dragoon + Ful'Mina)
- Max (Ful'Mina = 100%)

**Comment by DevJackSmith** [comment]
By none you mean Any. Because they are not limited by no wind, and no rain. And by storm you mean both levels are at least that high, but one of them could be higher?

**Comment by tsitu** [comment]
Yup!
