### ISSUE TITLE
Record trap power and luck in hunts

### ISSUE THREAD

**Issue by groupsky** [DevJackSmith/mh-hunt-helper#38]
I saw that the trap power and luck is sent to server with each hunt, but can't see that it is recorded. This would be helpful for determining mouse powers.

**Comment by DevJackSmith** [comment]
Hi @groupsky, I'm recording it in the hunts table. Are you talking about seeing it in the user history page or where?

**Comment by groupsky** [comment]
Must be a new addition, as I was checking the db dump available and couldn't find the fields. Now I checked the code and they are actually recorded. 

Closing as this ticket is obsolete.
