### ISSUE TITLE
Database Dump as CSV

### ISSUE THREAD

**Issue by AardWolf** [DevJackSmith/mh-hunt-helper#45]
Enhancement request, could you add or change the database dump to something more universal? Such as a csv?

I did get data and worked with it by loading your current dump into a mariadb database then running:
`mysqldump --skip-add-drop-table --skip-add-locks --compatible=db2 --skip-create-options -h localhost -u root -r mhhh_dump.sql -T tabs mhhh`

**Comment by DevJackSmith** [comment]
definitely, good idea

**Comment by DevJackSmith** [comment]
done
