### ISSUE TITLE
Explanation of different DB dumps

### ISSUE THREAD

**Issue by groupsky** [DevJackSmith/mh-hunt-helper#56]
Just noticed you added `latest` along with `nightly` backups. What is the difference between the two?

**Comment by DevJackSmith** [comment]
latest backs up once a week, nightly is every night

**Comment by DevJackSmith** [comment]
changed latest to weekly, which as they age become older1, older2.

**Comment by groupsky** [comment]
What is the point in keeping two backups at the same time, when the repo history is keeping all committed backups?

**Comment by DevJackSmith** [comment]
just easier access, don't have to search through repo. I want to clean up history sometimes, as the repo is getting too large, so if I clear history, at least I'll have 3 remaining. But I can remove those older backups too.
