### ISSUE TITLE
Add Lim's scripts link to popup

### ISSUE THREAD

**Issue by DevJackSmith** [DevJackSmith/mh-hunt-helper#97]
I want to add a link to Lims and other scripts, but the problem is I don't want to popularize the bot scripts.

**Comment by tsitu** [comment]
Perhaps add a link to my Reddit thread? I'll be keeping it updated for the foreseeable future, and I only include scripts that I've verified.

https://www.reddit.com/r/mousehunt/comments/avazpr/resource_useful_userscripts/

There's likely no way to stop people from finding and using bot scripts if that's what they've committed to doing, so my strategy is to not even mention them.

**Comment by tehhowch** [comment]
Given the latest reasoning in the Opera rejection, settling for a link may be the only option

**Comment by DevJackSmith** [comment]
we can add his scripts in the extension (if lim still approves of me doing that), we just can't load them from remote location.

**Comment by tsitu** [comment]
Added in [#39](https://github.com/DevJackSmith/mh-helper-extension/pull/39)
